### ISSUE TITLE
this.log is not a function crash

### ISSUE THREAD

**Issue by hootener** [mirusresearch/firehoser#4]
I'm receiving this error when using firehoser, it seems to occur when I use attempt to process a large number of events:

```
/home/app/node_modules/aws-sdk/lib/request.js:31
            throw err;
            ^

TypeError: this.log is not a function
    at Response.<anonymous> (/home/app/node_modules/firehoser/firehoser.js:108:26)
    at Request.<anonymous> (/home/app/node_modules/aws-sdk/lib/request.js:360:18)
    at Request.callListeners (/home/app/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/home/app/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/home/app/node_modules/aws-sdk/lib/request.js:673:14)
    at Request.transition (/home/app/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/app/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/app/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/app/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/app/node_modules/aws-sdk/lib/request.js:675:12)```

```
The offending code looks to be the `this.log` statement in line 108 of firehoser.js:

```
// Push errored records back into the next list.
            for (let [orig, result] of _.zip(records, resp.RequestResponses)){
                if (!_.isUndefined(result.ErrorCode)){
                    this.log(`Got ErrorCode ${result.ErrorCode} for record ${orig}`,'error'); // <- right here
                    leftovers.push({
                        type: "firehose",
                        description: result.ErrorMessage,
                        details: {
                            ErrorCode: result.ErrorCode,
                            ErrorMessage: result.ErrorMessage,
                        },
                        originalRecord: orig,
                    });
                }
            }
```

Defaulting the log output to just dump to the console in firehoser.js prevents the problem, like this:
`this.log = logger ? logger : (string) => {console.log(string)};`, but probably isn't the answer you're looking for.

Any thoughts on how to proceed?

**Comment by EyePulp** [comment]
@hootener Thanks for reporting the issue -- I've pushed a fix to the local repo and will test tomorrow to see if it corrects the issue.  You're welcome to try this repo directly or wait until I publish to npm once we're happy with the fix.

**Comment by EyePulp** [comment]
@hootener did some more digging, and beefed up the solution a bit with tests.  Should be in a better place now, and will publish after I test it on our stack tomorrow.
